/**
 * 全站圖示登記(新增圖示時在此登記,頁面不直接 import lucide)。
 * 名稱也用於 BFF 選單 / 目錄的 icon 欄位(「選單管理」只能選這裡登記的名稱)。
 */
import * as L from 'lucide-vue-next';
import type { Component } from 'vue';

export const ICONS: Record<string, Component> = {
  dashboard: L.LayoutDashboard,
  gateway: L.Network,
  settings: L.Settings,
  users: L.Users,
  user: L.User,
  shield: L.ShieldCheck,
  key: L.KeyRound,
  route: L.Route,
  server: L.Server,
  layers: L.Layers,
  activity: L.Activity,
  bell: L.Bell,
  sun: L.Sun,
  moon: L.Moon,
  logout: L.LogOut,
  login: L.LogIn,
  'chevron-down': L.ChevronDown,
  'chevron-right': L.ChevronRight,
  'chevron-left': L.ChevronLeft,
  menu: L.Menu,
  search: L.Search,
  plus: L.Plus,
  edit: L.Pencil,
  lock: L.Lock,
  unlock: L.LockOpen,
  refresh: L.RefreshCw,
  download: L.Download,
  check: L.Check,
  x: L.X,
  alert: L.TriangleAlert,
  'alert-circle': L.CircleAlert,
  info: L.Info,
  clock: L.Clock,
  release: L.GitBranch,
  eye: L.Eye,
  'eye-off': L.EyeOff,
  filter: L.Funnel,
  building: L.Building2,
  sparkles: L.Sparkles,
  database: L.Database,
  'trend-up': L.ArrowUpRight,
  'trend-down': L.ArrowDownRight,
  list: L.List,
  grid: L.LayoutGrid,
  graph: L.Share2,
  external: L.ExternalLink,
  'panel-close': L.PanelLeftClose,
  'panel-open': L.PanelLeftOpen,
  rocket: L.Rocket,
  audit: L.ScrollText,
  ticket: L.Ticket,
  gauge: L.Gauge,
  zap: L.Zap,
  'user-plus': L.UserPlus,
  'user-x': L.UserX,
  'user-check': L.UserCheck,
  reset: L.RotateCcw,
  'check-circle': L.CircleCheck,
  'x-circle': L.CircleX,
  workflow: L.Workflow,
  boxes: L.Boxes,
  fingerprint: L.Fingerprint,
  save: L.Save,
  undo: L.Undo2,
  globe: L.Globe,
  cpu: L.Cpu,
  monitor: L.Monitor,
  wifi: L.Wifi,
  code: L.Code,
  minus: L.Minus,
  hash: L.Hash,
  calendar: L.Calendar,
  repo: L.FolderGit2,
  spec: L.ListChecks,
  // 通知中心與公告編輯器(Gateway NOTIFY-PLAN)
  send: L.Send,
  megaphone: L.Megaphone,
  'bell-ring': L.BellRing,
  'check-check': L.CheckCheck,
  mail: L.Mail,
  upload: L.Upload,
  trash: L.Trash2,
  bold: L.Bold,
  italic: L.Italic,
  underline: L.Underline,
  strike: L.Strikethrough,
  h2: L.Heading2,
  h3: L.Heading3,
  'list-ordered': L.ListOrdered,
  quote: L.Quote,
  link: L.Link,
  image: L.Image,
  table: L.Table,
  'table-row': L.Rows3,
  'table-col': L.Columns3,
  palette: L.Palette,
  redo: L.Redo2,
  'align-left': L.TextAlignStart,
  'align-center': L.TextAlignCenter,
  'align-right': L.TextAlignEnd,
  // 應用切換(與 giga-Portal 同步)
  apps: L.Grip,
  home: L.House,
  'arrow-right': L.ArrowRight,
};

export const ICON_NAMES = Object.keys(ICONS).sort();
export const hasIcon = (name: string | null | undefined): name is string => !!name && name in ICONS;
export const FALLBACK_ICON = L.CircleAlert;
